### ISSUE TITLE
Everything logs at info level

### ISSUE THREAD

**Issue by remotezygote** [Carlangueitor/winston-koa-logger#2]
Due to order of `logLevel` ifs. PR incoming.

**Comment by davegw** [comment]
Submitted a fix for this same issue as well in #1. @Carlangueitor could you please take a look when you have a moment.

**Comment by remotezygote** [comment]
Maybe one of ours will be looked at eventually...

**Comment by Carlangueitor** [comment]
Sorry for the inactivity, the fix is merged now 👍

**Comment by davegw** [comment]
Thank you 👍
